In [20]:
#write a program to showcase a basic probablistics models in machine learning.
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

In [22]:
iris=load_iris()
x=iris.data
y=iris.target
print("first five data variable=",x[:5])
print('first five target variable=',y[:5])




first five data variable= [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
first five target variable= [0 0 0 0 0]


In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
model=GaussianNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)

print(f"model accuracy={accuracy*100:.2f}%")

sample=x_test[0].reshape(1,-1)
predicted_class=model.predict(sample)

print(f"predicted class of sample:{iris.target_names[predicted_class][0]}")




model accuracy=97.78%
predicted class of sample:versicolor
